### ISSUE TITLE
注册逻辑修正

### ISSUE THREAD

**Issue by asceking** [VictorHuu/PetFosterSystem#2]
![C69L8%GFN%)VIAO M @D3`7](https://github.com/VictorHuu/PetFosterSystem/assets/71561494/75834bc5-b7da-4e5a-b0ba-fc77826ae262)

**Comment by VictorHuu** [comment]
多虑了，数据库中存在暗含的序列，每注册一位，递增一位，就像某开放世界游戏不会存在重复的UID
