### ISSUE TITLE
提交寄养申请表

### ISSUE THREAD

**Issue by asceking** [VictorHuu/PetFosterSystem#3]
提供宠物名、宠物类型、寄养开始时间、寄养天数、备注信息，将申请表存入数据库，标注为“未审核”的状态

Discussion：从用户角度出发，是否应该让前端把“天数”改成“寄养结束时间”？（接口你们就按数据库的格式来就好，如果要改的话在我的Controller这一层应该就能转）（数据库的格式是什么来着？）

附录（主要给我自己看）：目前前端提供的数据
`const foster_table = {
        name: form.name,
        type: radio.value, 
        radio3: radio3.value,
        date1: form.date1,
        num: form.num,
        desc: form.desc,
      };`
name:宠物昵称；type:宠物类型；radio3:宠物类型进一步细分（eg：大中小型犬）；date1:寄养开始时间；num：寄养天数；desc：备注文字

**Comment by VictorHuu** [comment]
```
Discussion：从用户角度出发，是否应该让前端把“天数”改成“寄养结束时间”？
```
是的，寄养结束时间更好，你说的对，其实数据库底层弄个视图就可以。但数据库需要修改
*(前端真的好任性，我修改数据库还得考虑好多数据库设计的细节)*

![image](https://github.com/VictorHuu/PetFosterSystem/assets/103842499/c8352b22-9a08-4e1c-a168-f7cd0e5ccd54)

 前端接口有问题，打回去修改：
 单纯的宠物名容易出现重名现象，现在想到两种方案：
1. 必须用宠物ID
2. 输入宠物的昵称前几位，就会根据正则匹配显示出符合条件的宠物的肖像、昵称、UID（我觉得这种更好，不知道前端能不能在输入框输入时触发查询事件）。
3. desc是降序，备注应该是remark/note
4. radio3应该是size_radio，为了可读性。
5. 宠物类型指原有pet表的breed吗，如果是，那就不用传入type了，否则，前端需要说明想到的宠物类型有哪些。
6. 补充需要**寄养**的房间，可以考虑不补充，然后由系统自动分配。

**Comment by VictorHuu** [comment]
不，而是在axios 更新的issue下追加评论就行了。

**Comment by VictorHuu** [comment]
@asceking @M2030123 
```c#
        public static void CensorFoster(int censorstate=0,int Limitrow = -1, string Orderby = null)；//展示待审核/审核通过/未通过的界面等
       public static int ApplyFoster(string UID, string Petname,string Breed,string size, DateTime dateTime, int duration, string remark);//申请寄养
       public static void Censorship(string UID, int PID, DateTime date,int censorcode);//审核寄养
```
以上3个接口已经编写完成，请查看这三处代码的diff与主仓库的Draft PR #8
JSON文件也已更新。
 

- [ ] 孟负责剩余错误逻辑的处理，往JSON里添加必要的错误处理数组，但是要看清楚之前已经有的不要再添加。
- [ ] 葛一飞负责前后端接口，多余或缺少先用假设值，然后再在这个issue里提出来不一致的部分。
