### ISSUE TITLE
（管理员）获取/修改寄养申请表

### ISSUE THREAD

**Issue by asceking** [VictorHuu/PetFosterSystem#4]
1. 向数据库获取寄养申请表数据，建议将“审核状态”作为一个参数（？）（因为现在只要“未审核”的，但以后可能要展示所有历史）

返回的申请表数据应该包含：

寄养开始日期
ID（对应数据库的什么？申请表的ID吗？）
宠物ID
申请人UID
寄养天数
审核状态

2. 修改申请表的审核状态（仅可修改审核状态）

同理，如果存在寄养天数/截止日期的问题，在Controller转换

**Comment by VictorHuu** [comment]
说的很好，收到了
