### ISSUE TITLE
各页面数据交互逻辑

### ISSUE THREAD

**Issue by shiguangbiyi** [VictorHuu/PetFosterSystem#5]

**Comment by shiguangbiyi** [comment]
个人页面
[Uploading 我的页面数据交互逻辑.docx…]()

**Comment by shiguangbiyi** [comment]
个人页面
[我的页面数据交互逻辑.docx](https://github.com/VictorHuu/PetFosterSystem/files/12217157/default.docx)

**Comment by DaenerysTar** [comment]
### **领养部分（分为三个页面）**

### 1. 领养主页：
用户查询：宠物种类{猫、狗}、宠物性别{公、母}、宠物年龄{实际上是宠物出生时间}
展示：宠物种类{猫、狗}、宠物性别{公、母}、宠物年龄{实际上是宠物出生时间}、宠物的一张照片
（对宠物的筛选功能前端已经实现了，不知道后端还用不用写）

### 2. 单只宠物领养页面：
展示：宠物名字、宠物ID、宠物种类{猫、狗}、宠物性别{公、母}、宠物年龄{实际上是宠物出生时间}、宠物健康状况{良好、较差}、宠物是否接种疫苗{是、否}、宠物人气、宠物介绍、宠物的多张照片（如果多张照片不方便，可以改为一张）、宠物点赞量、宠物评论量、宠物收藏量、每条评论的评论用户、每条评论的评论时间（年月日，几点几分）、每条评论的内容

### 3. 领养申请表页面：
用户输入：领养人姓名、领养人性别{男、女}、领养人手机号、领养时间（年月日）、有无猫狗饲养经验{有、无}、是否可以坚持长期养护{是、否}、宠物生病是否愿意为它治病{是、否}、每天能留出多少时间照顾猫狗（小时）、领养后主要照顾猫狗的人是谁、家庭居住人口、家庭中是否有孩子{是、否}、是否愿意接受志愿者微信（视频、照片）的上门回访{是、否}

**Comment by DaenerysTar** [comment]
### 论坛部分

### 2. 论坛页面：
展示（多个帖子）：帖子标题、发帖时间（年月日，几点几分）、帖子阅读量、帖子点赞量、帖子评论量
用户输入：帖子标题（用于搜索，这个搜索功能前端已经实现了，不知道后端还用不用写）

### 2. 帖子页面：
展示：帖子标题、帖子作者、帖子内容、帖子点赞量、帖子评论量、帖子收藏量、每条评论的评论用户、每条评论的评论时间（年月日，几点几分）、每条评论的内容

### 3. 我要发帖页面：
用户输入：帖子标题、帖子内容、帖子中的图片（如果有的话）

**Comment by VictorHuu** [comment]
@DaenerysTar
> 展示（多个帖子）：帖子标题、发帖时间（年月日，几点几分）、帖子阅读量、帖子点赞量、帖子评论量
> 用户输入：帖子标题
>（用于搜索，这个搜索功能前端已经实现了，不知道后端还用不用写）

涉及到持久存储就需要后端和数据库，帖子如果要有图片那么帖子内容需要改为CLOB与BLOB存储，具体方案略。

> 用户输入：领养人姓名、领养人性别{男、女}、领养人手机号、领养时间（年月日）、有无猫狗饲养经验{有、无}、是否可以坚> 持长期养护{是、否}、宠物生病是否愿意为它治病{是、否}、每天能留出多少时间照顾猫狗（小时）、领养后主要照顾猫狗的人> 是谁、家庭居住人口、家庭中是否有孩子{是、否}、是否愿意接受志愿者微信（视频、照片）的上门回访{是、否}

这么多内容可以实现，但需要分配到多个表，**领养人需要提供UID，毕竟已经登陆了，领养人的基本信息在注册时已经确定，除了性别**，后面的话这些大量信息，我可以考虑存放到另外一张表。

其他的没什么问题。

**Comment by VictorHuu** [comment]
> 展示：宠物名字、宠物ID、宠物种类{猫、狗}、宠物性别{公、母}、宠物年龄{实际上是宠物出生时间}、宠物健康状况{良好、较  
> 差}、宠物是否接种疫苗{是、否}、**宠物人气**、宠物介绍、宠物的多张照片（如果多张照片不方便，可以改为一张）、宠物点赞
> 量、宠物评论量、宠物收藏量、每条评论的评论用户、每条评论的评论时间（年月日，几点几分）、每条评论的内容

- [ ] 作为专业的宠物网站，宠物种类也太粗糙了，看value.json里面找有哪些健康状况，然后做成下拉框。
- [ ] 宠物人气的算法是什么？
- 对于后端来说， 这个展示需要分开，一部分展示除了具体评论以外的内容，另一部分展示具体内容。
- 一张图片就够了，实现也可以实现，我懒得实现。
@DaenerysTar 
ASAP

**Comment by DaenerysTar** [comment]
关于宠物人气的算法
我觉得最简单的方法就是点赞量+评论量+收藏量……
如果不看时间，也就是改改权重
然后如果引入时间衰减机制就麻烦很多
就是每一个点赞、评论、收藏都乘一个e^-(该点赞/评论/收藏距今的天数)
我觉得宠物人气要不就简单一点算吧
帖子这种本身就有时效性的东西倒是比较适合引入时间衰减机制
就是（点赞量 + 评论量 + 收藏量）*e^-(发帖时间)

**Comment by VictorHuu** [comment]
@DaenerysTar 我觉得给点赞，评论，收藏不同的权重，分别为1,5,10，这样好也简单

**Comment by aodef** [comment]
管理员页面数据交互逻辑
在审核领养界面
首先有一个获取从数据库获取数据的api:  ‘/api/manage-adopt’

interface AdoptionRecord {
  date: string
  Id:string
  petId: string
  userId: string
  reason: string
  censor_status:string
}
要获取的数据类型是这样的数组，然后我注意到当时我们设计的adopt表只有time_ID, adopter_ID以及pet_ID,所以应该要加入id以唯一识别每项申请，还要加入收养的理由reason（可能比较长）这两项属性，并且要将time_ID对应的时间转化成如“2022-3-21“这样的string类字符。

另外一个api是修改审核属性的：
对应有两种情况
 await axios.patch(`/api/manage-adopt-update/${recordToUpdate.Id}`, { censor_status: 'abored' });
await axios.patch(`/api/manage-adopt-update/${recordToUpdate.Id}`, { censor_status: 'legitimate' });




在审核寄养界面
首先有一个获取从数据库获取数据的api:  ‘/api/manage-foster’
interface FosterRecord {
  date: string
  id:string
  petId: string
  userId: string
  days: number
  censor_status: string
}
要获取的数据类型是这样的数组，然后我注意到当时我们设计的foster表只有time_ID, foster_parent以及pet_ID和duration,所以应该要加入id以唯一识别每项申请，并且要将time_ID对应的时间转化成如“2022-3-21“这样的string类字符。

另外一个api是修改审核属性的：
对应有两种情况
await axios.patch(`/api/manage-foster-update/${recordToUpdate.id}`, { censor_status: 'abored' });
await axios.patch(`/api/manage-foster-update/${recordToUpdate.id}`, { censor_status: 'legitimate' });

**Comment by aodef** [comment]
这部分的代码是已经上传过的，由于和组长叙述的管理员页面中审核领养与寄养的逻辑有更改，所以特别再上传一次。以上逻辑和代码逻辑是一致的，主要是方便后端同学阅读代码。

**Comment by VictorHuu** [comment]
@aodef 人与宠物确定就可以确定领养关系，因为是终身领养。同理，加上时间也可以确定寄养关系，后端已经有了时间区间不重复的逻辑判断了。ID用作物或人的标识比较好。

**Comment by VictorHuu** [comment]
@aodef 涉及到数据库的序列，主码改动，那么就可能涉及到关联表的外码改动，涉及到后端的所有层的改动，这一点都不方便。所以foster的接口还是这样：
```json
"censor_state":[
    "to be censored",
    "aborted",
    "legitimate",
    "outdated",
    "invalid",
    "at capacity"
  ],
```
```c#
//censorcode表示审核通过还是不通过，具体在values.json中查询
void Censorship(string UID, int PID, DateTime date,int censorcode=0);
```
@DaenerysTar 
> 用户输入：领养人姓名、领养人性别{男、女}、领养人手机号、领养时间（年月日）、有无猫狗饲养经验{有、无}、是否可以坚> 持长期养护{是、否}、宠物生病是否愿意为它治病{是、否}、每天能留出多少时间照顾猫狗（小时）、领养后主要照顾猫狗的人> 是谁、家庭居住人口、家庭中是否有孩子{是、否}、是否愿意接受志愿者微信（视频、照片）的上门回访{是、否}

这里面就没有输入宠物也没有输入物种，因此我只能自动随机分配,审核通过执行以下函数：
```
int CensorAdopt(string UID,string species,out int errcode);
```

**Comment by VictorHuu** [comment]
@aodef 
> 非主键属性完全依赖于候选键（主键）而不是依赖于部分候选键

你的请求破坏了3NF，会造成部份依赖的问题。

**Comment by aodef** [comment]
我说的是管理员界面的寄养领养审核的接口，不是主页面寄养领养的接口。

**Comment by aodef** [comment]
那时间可以唯一确定一条领养，寄养数据吗？主要是后端要告诉我我要传哪个可以唯一一条数据 @VictorHuu

**Comment by aodef** [comment]
那时间可以唯一确定一条领养，寄养数据吗？主要是后端要告诉我我要传哪个可以唯一确定一条数据 @VictorHuu

**Comment by VictorHuu** [comment]
@aodef 可以，一天领养，寄养一只还算是合理的规则。

**Comment by aodef** [comment]
但是我是指的所有用户，就相当于所有用户一天只能寄养，领养一只？这不太合理吧

**Comment by aodef** [comment]
但是我是指的所有用户，就相当于所有用户一天只能寄养，领养一只？这不太合理吧 @VictorHuu 就是哪个寄养，领养的表的主码到底是什么？

**Comment by VictorHuu** [comment]
@aodef 合理的，主码是用户+宠物+事件，不可能一个用户一天反复领养同一只宠物

**Comment by aodef** [comment]
我现在有点晕，就是上周五应该管理员界面的领养，寄养审核就上传了，你们是不是没有看到呀？然后管理员界面和主界面的寄养，领养是两个东西，应该是不同的接口，主界面只有寄养是我负责的

**Comment by aodef** [comment]
@VictorHuu 那我就传三个参数date: string petId: string userId: string回去唯一确定？

**Comment by VictorHuu** [comment]
@aodef 是的

**Comment by aodef** [comment]
okok，有更改后我再上传

**Comment by thesamechen** [comment]
### **公告界面**
**1.主界面：**
用户输入：公告标题
展示（公告列表）：公告标题、公告发布时间（可以按照公告发布时间排序）
点击公告列表中的公告进入详情界面

**2.公告详情界面：**
展示：公告标题、公告内容、公告发布时间、（公告ID）

**Comment by DaenerysTar** [comment]
第一个问题就是之前说过宠物的种类太少，所以我想猫狗各分一类做成下拉框，但是这里只有狗的品种，我想问问后端，把values.js里面这个breed改成一个breed1用来放狗的品种，再弄一个breed2用来放猫的品种，这样可以吧？不会对其他代码造成影响吧？
"breed": {
      "德国牧羊犬": "German Shepherd",
      "拉布拉多猎犬": "Labrador Retriever",
      "金毛猎犬": "Golden Retriever",
      "斗牛犬": "Bulldog",
      "比格犬": "Beagle",
      "贵宾犬": "Poodle",
      "罗威纳犬": "Rottweiler",
      "约克夏梗": "Yorkshire Terrier",
      "拳师犬": "Boxer",
      "腊肠犬": "Dachshund"
    },

还有一个问题就是后端之前说把宠物的年龄改成了出生日期（年月日），前端需要把宠物的生日转换为年龄显示在页面上，但是宠物救助站里的宠物一般只能估算一个年龄，应该确定不了具体的出生日期吧，不知道这个怎么解决？以及我不是很了解后端的代码，不知道宠物表的定义在哪个文件里？

**Comment by DaenerysTar** [comment]
我刚找到宠物表了，不好意思打扰了

**Comment by DaenerysTar** [comment]
收到收到，我的API真是看着就头疼，哭

**Comment by VictorHuu** [comment]
@DaenerysTar 这是后端代码https://github.com/VictorHuu/PetFosterSystem/blob/pioneer/Glue/PetFosterBLL/AdoptApplyManager.cs

**Comment by DaenerysTar** [comment]
收到，我看一看

**Comment by VictorHuu** [comment]
@DaenerysTar 我把物种改为PID——宠物ID了，你想办法传就行。还有人医院申请预约，医生都没选。
```C#
public static int ApplyAdopt(string UID, string PID,bool gender, bool pet_exp, bool long_term_care,
            bool w_to_treat, decimal d_care_h, string P_Caregiver, decimal f_popul, bool be_children, bool accept_vis);
public static int CensorAdopt(string UID,int pid,out int errcode);
```

**Comment by VictorHuu** [comment]
https://github.com/VictorHuu/PetFosterSystem/issues/5#issuecomment-1672556179
@thesamechen 公告搜索与展示功能后端逻辑已完成。
```C#
public static void ShowBulletinVerbose(string BID);
public static void ShowBulletins(string text);
```
其中text为用户输入，用户搜索时只要用分隔符分开关键词，就可以查询公告了，比如’&‘,'空格，逗号，句号，'和','\','/'

**Comment by DaenerysTar** [comment]
确认一下子，后端是打算把单个宠物页面的评论功能给去掉吗？因为我在宠物表里没有看见

**Comment by DaenerysTar** [comment]
还有，宠物人气属性也没找到呀

**Comment by VictorHuu** [comment]
@DaenerysTar 这些功能都放到一个表中不符合范式
pet_profile视图有
![image](https://github.com/VictorHuu/PetFosterSystem/assets/103842499/c31bff99-b4a1-4c20-94fc-bf7db091c2b8)。
一个功能的处理涉及到三四个表，最后合并为一个视图方便查询。

**Comment by DaenerysTar** [comment]
收到收到

**Comment by DaenerysTar** [comment]
我刚想起评论区需要显示用户头像，所以用户还得加一个属性。好弄吗，不好弄删了

**Comment by VictorHuu** [comment]
@DaenerysTar 可以，但是头像需要预压缩然后再传送到数据库，**小于200K**，得提供方便上传修改图像的接口，不然后端也不方便直接提供数据。

**Comment by DaenerysTar** [comment]
收到
